name: "Run aries-vcr"
description: "Build and run Aries-vcr (vanilla version)"
author: "iancostanzo@gmail.com"
runs:
  using: "composite"
  steps:
    - name: checkout-aries-vcr
      run: git clone https://github.com/ianco/aries-vcr.git
      shell: bash
    - name: build-aries-vcr
      run: ./manage build
      shell: bash
      working-directory: aries-vcr/docker
    - name: run-aries-vcr
      run: ./manage start --wait
      shell: bash
      working-directory: aries-vcr/docker
branding:
  icon: "cloud-lightning"
  color: "blue"
